apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-service
  labels:
    app: go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      # 1. The Main Application
      - name: go-app
        # This is the line the pipeline will automatically update
        image: ghcr.io/jaimindevops/go-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_HOST
          value: "redis-service"
        
      # 2. The Sidecar (For Debugging)
      - name: sidecar
        image: alpine
        command: ["/bin/sh", "-c", "sleep 3600"]
